// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuY97kVqjSYVWfAdU50bnCs4zx7lB04A8',
    appId: '1:363928542978:web:007b79787bdeea07c92c1b',
    messagingSenderId: '363928542978',
    projectId: 'groceria-1f15d',
    authDomain: 'groceria-1f15d.firebaseapp.com',
    storageBucket: 'groceria-1f15d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxeOaOGBP1pLbEHXKr90HWsFRQsoGmKY',
    appId: '1:363928542978:android:2ddd2a2c0f3dd38fc92c1b',
    messagingSenderId: '363928542978',
    projectId: 'groceria-1f15d',
    storageBucket: 'groceria-1f15d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwXICCX0t40NFAnW_AkSv8ZwO3P9_pHQA',
    appId: '1:363928542978:ios:2d8991b48573103cc92c1b',
    messagingSenderId: '363928542978',
    projectId: 'groceria-1f15d',
    storageBucket: 'groceria-1f15d.firebasestorage.app',
    iosBundleId: 'com.example.kingKalasan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwXICCX0t40NFAnW_AkSv8ZwO3P9_pHQA',
    appId: '1:363928542978:ios:2d8991b48573103cc92c1b',
    messagingSenderId: '363928542978',
    projectId: 'groceria-1f15d',
    storageBucket: 'groceria-1f15d.firebasestorage.app',
    iosBundleId: 'com.example.kingKalasan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuY97kVqjSYVWfAdU50bnCs4zx7lB04A8',
    appId: '1:363928542978:web:19539c9474b6cfffc92c1b',
    messagingSenderId: '363928542978',
    projectId: 'groceria-1f15d',
    authDomain: 'groceria-1f15d.firebaseapp.com',
    storageBucket: 'groceria-1f15d.firebasestorage.app',
  );
}
